### PR TITLE
Fix: Certification drop-down menu remembers un-saved changes

### LINKED ISSUE #238: Certification drop-down menu remembers un-saved changes
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**To Reproduce**
1. Go to “Create class” or “Edit Class” page, and change the selections of certifications
2. Click on “Cancel”
3. Go back to the “Create class” or “Edit Class” page and open the drop-down certifications drop-down menu
4. The canceled changes are pre-selected.

**Expected behavior**
Make sure the Certifications drop-down shows the correct previously saved certifications selections

### PR DESCRIPTION
**Pull request by snowblind7899**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #238 

Authors: Jason Chan, Diego Vega, and Siyuan Zhai

This fixes the issue by having the cancel actions in ClassInviteTable.js and modal.js revert to previously saved dropdown changes and clearing all selected dropdown options, respectively.

i.e., canceling while editing class certifications will revert selected dropdown options back to last saved certifications, and canceling while creating a new class will unselect any changes.

### CODE REVIEW

**Comment by GuillermoFloresV** [comment]
Hi there, thanks to the team for taking on this issue! 

I was wondering why changes were made to the Prisma version inside of `package.json`. I assume that this change caused your `package-lock.json` to have ~7600 deletions which are also causing your merge conflicts.

**Comment by snowblind7899** [comment]
Ah sorry about those, I believe those are due to running an npm update or somewhere among the npx commands. It should be safe to keep the current package-lock.json and package.json and disregard the new versions.

**Comment by snowblind7899** [comment]
i will close this PR and remedy the issue

**Comment by snowblind7899** [comment]
I have reverted the package.json and package-lock.json to the current classroom versions, so the merge conflict should be resolved now

**Review by GuillermoFloresV — APPROVED** [review]

**Pull request merged**
