### PR TITLE
feat: add Modal Snapshot test

### PR DESCRIPTION
**Pull request by Chrisdbeloved1**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Solving #309 

Created a Snapshot testing for the modal component.

Co-authored-by: Ayomide Onifade <onifadeayomide328@gmail.com>
Co-authored-by: Quawiyyah Abdulhameed <abdulhameedqo@gmail.com>
Co-authored-by: Hamzat Oluwabori <oluwaborihamzat@gmail.com>

### CODE REVIEW

**Comment by lloydchang** [comment]
a new test was added, which is creating issues for all new PRs

https://github.com/freeCodeCamp/classroom/pull/396
by @lloydchang 

https://github.com/freeCodeCamp/classroom/pull/397
by @theGaryLarson 

https://github.com/freeCodeCamp/classroom/pull/398
by @Komal914 

https://github.com/freeCodeCamp/classroom/pull/399
by @Chrisdbeloved1, @Ayomide6441, @Quawiyyah, @Code-Victor

all show the same failing test, dashtable_v2, from https://github.com/freeCodeCamp/classroom/pull/366#issuecomment-1652616915

**Comment by lloydchang** [comment]
Please contact @GuillermoFloresV if you have further questions about this. Thanks!

**Comment by lloydchang** [comment]
From https://codedayorg.slack.com/archives/C05ENB1VAKT/p1691946767049949
> @Chrisdbeloved1, @Code-Victor, @Quawiyyah, @Ayomide6441
I believe you will need to fix the failing test by updating the Jest snapshot files to match — Otherwise, your pull request cannot be merged by the pull request reviewers.
**https://github.com/freeCodeCamp/classroom/pull/399**
> **Classroom ci / Build and test (16.14.2) (pull_request) Failing after 49s**
**https://github.com/freeCodeCamp/classroom/actions/runs/5842433790/job/15843553089?pr=399**
[ⓧ Run tests 4s](https://github.com/freeCodeCamp/classroom/files/12330506/Run.tests.4s.txt)

**Comment by Code-Victor** [comment]
> 

The error occured because UI was updated recently to support toast notifications. we are about to update the snapshot too.

**Review by utsab — APPROVED** [review]
Thank you for creating this test.  I appreciate that you tested the case where the user clicks on the header.  I didn't know you could simulate the click through a snapshot test!

**Pull request merged**
