### PR TITLE
build(.devcontainer): support GitHub Codespaces, newer Node.js and npm versions

### LINKED ISSUE #355: support GitHub Codespaces, newer Node.js and npm versions
See https://github.com/freeCodeCamp/classroom/pull/349

### PR DESCRIPTION
**Pull request by lloydchang**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #355

build(.devcontainer): support GitHub Codespaces
~ci(package.json): support newer Node.js and npm versions~

Fix `npm ci` error when using GitHub Codespaces.

### CODE REVIEW

**Comment by lloydchang** [comment]
Fix `npm ci` error when using GitHub Codespaces:

```
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ 
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ npm ci
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @freecodecamp/classroom@0.0.0
npm ERR! notsup Not compatible with your version of node/npm: @freecodecamp/classroom@0.0.0
npm ERR! notsup Required: {"node":"^16","npm":"^8"}
npm ERR! notsup Actual:   {"npm":"9.6.7","node":"v20.3.0"}

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2023-07-05T02_17_54_166Z-debug-0.log
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ node --version
v20.3.0
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ npm --version
9.6.7
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ npm ci

> @freecodecamp/classroom@0.0.0 prepare
> husky install

husky - Git hooks installed

added 889 packages, and audited 890 packages in 41s

157 packages are looking for funding
  run `npm fund` for details

31 vulnerabilities (30 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 9.6.7 -> 9.7.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
npm notice Run npm install -g npm@9.7.2 to update!
npm notice 
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ npm install -g npm@9.7.2

removed 16 packages, and changed 42 packages in 4s

28 packages are looking for funding
  run `npm fund` for details
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ npm ci

> @freecodecamp/classroom@0.0.0 prepare
> husky install

husky - Git hooks installed

added 889 packages, and audited 890 packages in 34s

157 packages are looking for funding
  run `npm fund` for details

31 vulnerabilities (30 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
@lloydchang ➜ /workspaces/freeCodeCamp-classroom (main) $ 
```
Screen Shot 2023-07-04 at 7 29 47 PM

**Comment by lloydchang** [comment]
Relates to https://github.com/freeCodeCamp/classroom/pull/205

**Comment by lloydchang** [comment]
Node.js 16 will be end-of-life in September:

From https://github.com/nodejs/release#release-schedule

> Release | Status | Codename | Initial Release | Active LTS Start | Maintenance Start | End-of-life
> -- | -- | -- | -- | -- | -- | --
> [16.x](https://nodejs.org/download/release/latest-v16.x/) | Maintenance | [Gallium](https://nodejs.org/download/release/latest-gallium/) | 2021-04-20 | 2021-10-26 | 2022-10-18 | [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/)

**Comment by lloydchang** [comment]
Screenshot of GitHub Codespaces after start-up and attaching to the Terminal:

Screen Shot 2023-07-05 at 8 07 42 PM

Using `postAttachCommand` (A command to run each time a tool has successfully attached to the container) to read the shell-evaluated `${CODESPACE_NAME}` variable.

https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace

**Comment by lloydchang** [comment]
**Good news!**

I tested this so that GitHub Codespaces and Gitpod are a parity.

Please see the screenshots below where the GitHub Codespaces screenshot looks the same as the Gitpod screenshot:

**GitHub Codespaces Screen Shot 2023-07-06 at 12 41 20 PM.png**

GitHub Codespaces Screen Shot 2023-07-06 at 12 41 20 PM

**Gitpod Screen Shot 2023-07-06 at 10.20.34 AM.png**

Gitpod Screen Shot 2023-07-06 at 10 20 34 AM

**Comment by lloydchang** [comment]
Cross-posted at https://discord.com/channels/692816967895220344/715074489422970962/1127463017244790904
> If anyone is available to review this pull request that I submitted, that would be wonderful:
> build(.devcontainer), ci(package.json): support GitHub Codespaces, newer Node.js and npm versions #349
> [ https://github.com/freeCodeCamp/classroom/pull/349](https://github.com/freeCodeCamp/classroom/pull/349)
> Thanks!

**Comment by GuillermoFloresV** [comment]
Hi Lloyd, 

Thanks for your PR! We have seen this and are working to be able to review all of our new PRs, but typically this is done by hand (pulling your changes onto my dev environment and testing for myself) so this can take a while with so many PRs.

However, I'll be reviewing this PR on Monday (07/09/23), just wanted to give you a heads-up that we have seen it.

Thanks for your contribution and patience!

**Review by GuillermoFloresV — APPROVED** [review]

**Pull request merged**
