### PR TITLE
fix: Stop showing dashed names when creating a classroom

### LINKED ISSUE #167: Stop showing dashed names when creating a classroom
**Describe the bug**
For the sake of UX, we can start to show normal titles (non-dashed) rather than dashed names when creating classrooms inside of our modal. This is a small change that can be tied to #151 but since this is past the scope of that specific bug, this issue was created and can be done separately. 

Current view of the modal: 
image

We store the non-dashed names inside of the same block where we store the dashed names so we can simply pass them along inside of our props when creating the modal.

### PR DESCRIPTION
**Pull request by OsCortes88**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #167
Co-authored by: Michelle Tan <michelle0223@gmail.com>
Co-authored by: Fadi Buni <fadibuni1@gmail.com>

Changed the title of the classes in the menu to title case format with no dashes.

Before:
PR Dashes

After:

PR Non-Dashes

### CODE REVIEW

**Comment by GuillermoFloresV** [comment]
Hi there, thanks for taking on this issue!

I wanted to make a quick note that we did not want to get rid of the dashed names outright, we want to **also** have the title (non-dashed) available to us in order to display them to the user. We use the dashed names in other areas of the app (and eventually will use them in our DB) and switching everything to the title name could end up causing us to refactor other code that does not need refactoring.

**Comment by michellejtan** [comment]
@GuillermoFloresV
so do not get rid of the dashed names...
For the sake of UX, you want to modify dashedName (dashed names) to show up non-dashed inside the modal like the following:
Screenshot 2022-11-15 195904

In addition, did you wanted the first letter of every word to be uppercase?

**Comment by GuillermoFloresV** [comment]
@michellejtan

Yes, we do not want to get rid of the dashed names completely. For the sake of UX, we want to have the non-dashed names displayed inside of the modal as described in #167.

You shouldn't need to alter the strings in any way since freeCodeCamp provides the proper names already. See the comment that Utsab left on the issue I've linked.

**Comment by OsCortes88** [comment]
@GuillermoFloresV

Thank you for the review. We have edited the file so we still conserve the dashedNames. I passed in another variable called displayName that holds the title we wanted. Let us know if this is what was intended.

**Review by GuillermoFloresV — APPROVED** [review]
LGTM!

**Comment by fadibuni** [comment]
@GuillermoFloresV Thanks!

**Pull request merged**
