### PR TITLE
fix: react hydration errors on admin

### LINKED ISSUE #359: 1 of 2 React Hydration — Error 1 of 3 errors in Admin view: Unhandled Runtime Error: Error: Hydration failed because the initial UI does not match what was rendered on the server.
**Describe the bug**
1 of 2 React Hydration — Error 1 of 3 errors in Admin view: Unhandled Runtime Error: Error: Hydration failed because the initial UI does not match what was rendered on the server.

**To Reproduce**
1. Go to Admin view

**Expected behavior**
Error message without the stack trace.

**Screenshots**
1 of 2 React Hydration — Error 1 of 3 errors in Admin view: Unhandled Runtime Error: Error: Hydration failed because the initial UI does not match what was rendered on the server.

Screen Shot 2023-07-06 at 10 20 34 AM (1)

```
1 of 3 unhandled errors

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Call Stack
throwOnHydrationMismatch
node_modules/react-dom/cjs/react-dom.development.js (12507:0)
tryToClaimNextHydratableInstance
node_modules/react-dom/cjs/react-dom.development.js (12535:0)
updateHostComponent
node_modules/react-dom/cjs/react-dom.development.js (19902:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21618:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)
```

Screen Shot 2023-07-06 at 10 24 12 AM

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 114.0.5735.198 (Official Build) (x86_64)

**Additional context**
Relates to
https://github.com/freeCodeCamp/classroom/issues/134
https://github.com/freeCodeCamp/classroom/issues/360
https://github.com/freeCodeCamp/classroom/issues/361

### LINKED ISSUE #360: 2 of 2 React Hydration — Error 2 of 3 errors in Admin view: Unhandled Runtime Error: Error: Hydration failed because the initial UI does not match what was rendered on the server.
**Describe the bug**
2 of 2 React Hydration — Error 2 of 3 errors in Admin view: Unhandled Runtime Error: Error: Hydration failed because the initial UI does not match what was rendered on the server.

**To Reproduce**
1. Go to Admin view

**Expected behavior**
Error message without the stack trace.

**Screenshots**
2 of 2 React Hydration — Error 2 of 3 errors in Admin view: Unhandled Runtime Error: Error: Hydration failed because the initial UI does not match what was rendered on the server.

Screen Shot 2023-07-06 at 10 20 34 AM (1)

```
 2 of 3 unhandled errors

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Call Stack
throwOnHydrationMismatch
node_modules/react-dom/cjs/react-dom.development.js (12507:0)
tryToClaimNextHydratableInstance
node_modules/react-dom/cjs/react-dom.development.js (12535:0)
updateHostComponent
node_modules/react-dom/cjs/react-dom.development.js (19902:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21618:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27426:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)
```

Screen Shot 2023-07-06 at 10 25 16 AM

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 114.0.5735.198 (Official Build) (x86_64)

**Additional context**
Relates to
https://github.com/freeCodeCamp/classroom/issues/134
https://github.com/freeCodeCamp/classroom/issues/359
https://github.com/freeCodeCamp/classroom/issues/361

### LINKED ISSUE #361: 1 of 1 React Suspense Boundary — Error 3 of 3 errors in Admin view: Unhandled Runtime Error: Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
**Describe the bug**
1 of 1 React Suspense Boundary — Error 3 of 3 errors in Admin view: Unhandled Runtime Error: Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

**To Reproduce**
1. Go to Admin view

**Expected behavior**
Error message without the stack trace.

**Screenshots**
1 of 1 React Suspense Boundary — Error 3 of 3 errors in Admin view: Unhandled Runtime Error: Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Screen Shot 2023-07-06 at 10 20 34 AM (1)

```
3 of 3 unhandled errors

Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Call Stack
updateHostRoot
node_modules/react-dom/cjs/react-dom.development.js (19849:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21615:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27426:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
recoverFromConcurrentError
node_modules/react-dom/cjs/react-dom.development.js (25850:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25750:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)
```

Screen Shot 2023-07-06 at 10 26 04 AM

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 114.0.5735.198 (Official Build) (x86_64)

**Additional context**
Relates to
https://github.com/freeCodeCamp/classroom/issues/134
https://github.com/freeCodeCamp/classroom/issues/359
https://github.com/freeCodeCamp/classroom/issues/360

### PR DESCRIPTION
**Pull request by Komal914**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #361 
Closes #360
Closes #359

This solution turns off server side rendering for the AdminTable component. I do not fully understand the benefits and tradeoffs of turning off server side rendering as I am still researching this topic. Let me know if you prefer server side to be on rather than off for AdminTable.

### CODE REVIEW

**Comment by lloydchang** [comment]
From [CodeDay Labs Slack](https://codedayorg.slack.com/archives/C05E350DQH4/p1690416497557639?thread_ts=1690413704.501539):

> Komal Kaur
>  [5:08 PM](https://codedayorg.slack.com/archives/C05E350DQH4/p1690416497557639?thread_ts=1690413704.501539)
> I was reading this:
> https://nextjs.org/docs/messages/react-hydration-error
> and tried solution 2
> 
> Lloyd Chang
>  [6:44 PM](https://codedayorg.slack.com/archives/C05E350DQH4/p1690422282712839?thread_ts=1690413704.501539)
> [@Komal Kaur](https://codedayorg.slack.com/team/U026LG2L51Q)
>  While you are reading some more… Since you already have a fix via "[solution 2](https://codedayorg.slack.com/archives/C05E350DQH4/p1690416497557639?thread_ts=1690413704.501539)," you can start preparing a pull request to solicit feedback publicly about "[solution 2](https://codedayorg.slack.com/archives/C05E350DQH4/p1690416497557639?thread_ts=1690413704.501539)," and note in the pull request that you are reading about SSR in case a different solution that retains SSR is preferred by the maintainers.

**Comment by lloydchang** [comment]
https://github.com/freeCodeCamp/classroom/pull/398
lgtm as a good enough solution because Admin view isn't intended for Search Engine Optimization (SEO).
I don't know why the errors was happening in the first place, but it may not matter if Server Side Rendering can be disabled for the Admin view.

**Comment by lloydchang** [comment]
@Komal914 I believe this is no longer needed because #361, #360, #359 errors no longer happens after #401

**Comment by GuillermoFloresV** [comment]
Hi, @Komal914, thanks for taking the initiative on this issue. 

What is the reasoning behind using `Promise.resolve(<AdminTable ... ><AdminTable/>`? Could we not import the adminTable component using next/dynamic like so: 
File: `pages/admin/index.js`
```javascript
// The rest of your code inside of /admin/index.js
export default function Home() {

  const AdminTable = dynamic (() => import('path/to/adminTable'), ssr: false,});
  // The rest of your code inside of /admin/index.js 

  return {
  // The rest of your return code inside of /admin/index.js
  <AdminTable />
  // The rest of your return code inside of /admin/index.js
  }
}
``` 
?

Regardless, another change I think that we should do is to deprecate our use of `react-data-table-component` inside of the admin page and instead opt for `react-table`. You can find examples of how it is used locally to the project inside of [dashtable v2](https://github.com/freeCodeCamp/classroom/blob/main/components/dashtable_v2.js). 

The hope is that we do not find this issue inside of our new table library since the one the admin table is currently using has caused lots of issues for us before. If it does, however, we can attempt this fix that you have.

**Comment by Komal914** [comment]
I did not realize we can simply import using dynamic with next.js. I will update this and add the react-table as requested.

**Review by utsab — APPROVED** [review]
Thank you @Komal914 and @theGaryLarson for fixing this hydration error.   Turning off server side rendering seems like a reasonable approach.

**Pull request merged**
