### PR TITLE
fix: Keep the previous selected certifications after editing

### LINKED ISSUE #226: Editing the topics for a classroom does not remember the previously chosen topoics
1. Create a new classroom.  Select at least one topic for the freeCodeCamp curriculum. 
2. Go to the edit page for a class
3. Click on the drop down for the classroom topics
4. Note that it does not remember which classes were previously selected.

### PR DESCRIPTION
**Pull request by Qianru69**
Co-authored-by: Shawn Templer <stemp001@ucr.edu>
Co-authored-by: Vanessa Valle <vallevanessa13@gmail.com>
Co-authored-by: Seth Villa <sethvilla13@gmail.com>

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #226

### CODE REVIEW

**Comment by GuillermoFloresV** [comment]
Hi Qianru & team, great work! Could you also fix something I just noticed? Inside the `ClassInviteTable.js` file, we set up our modal for editing classes. However, I noticed that the button that we are using inside of that edit modal says `Create` rather than `Update`. Would you or someone on the team be able to fix this before we approve the change since this is something related to the modal? 

I have attached a picture to show what I am talking about just in case I was not 100% clear. 

Thanks!
Screenshot 2023-01-30 103313

**Comment by Qianru69** [comment]
Hi Guillermo, thank you for the review. We've edited the "Create" button into "Update". 

> Hi Qianru & team, great work! Could you also fix something I just noticed? Inside the `ClassInviteTable.js` file, we set up our modal for editing classes. However, I noticed that the button that we are using inside of that edit modal says `Create` rather than `Update`. Would you or someone on the team be able to fix this before we approve the change since this is something related to the modal?
> 
> I have attached a picture to show what I am talking about just in case I was not 100% clear.
> 
> Thanks! Screenshot 2023-01-30 103313

**Comment by Qianru69** [comment]
Hi Guillermo, thank you for the review! We've edited the "Create" button into "Update".

**Review by GuillermoFloresV — APPROVED** [review]

**Comment by GuillermoFloresV** [comment]
Awesome, thanks for this fix. LGTM!

**Pull request merged**
