### PR TITLE
removed localhost:3000 from js files

### PR DESCRIPTION
**Pull request by yashnerkar**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by GuillermoFloresV** [comment]
Hi there, thanks for taking on this issue. Something to note is that the mention of localhost in the file you edited is specifically for copying a link to the user's clipboard. So the current state of the code would not fulfill that feature. Would you be able to change the code to also include the user's current domain name instead of `localhost`? (this is so when we copy the invite code, it will work correctly to copy the domain name+the invite code to the user's clipboard.)

Also, would you be able to edit your comment to mention that this closes issue #174 ? This just helps us keep the issues page up-to-date when someone fixes the issue.

Thanks!

**Comment by yashnerkar** [comment]
I have updated the url as per the requirement, domain name + invite code  can you check it

**Comment by GuillermoFloresV** [comment]
Hi there, sorry this must've gotten lost in all the failed Dependency Bot PRs. One small thing, could we change the `api` name to something that makes it a bit more explicit? Otherwise, this looks great and I will merge it once a more precise name has been pushed.

Thanks!

**Comment by yashnerkar** [comment]
yeah sure!

**Comment by GuillermoFloresV** [comment]
Sorry for the long turn around time, this is great. Thanks again!

**Review by GuillermoFloresV — APPROVED** [review]

**Comment by yashnerkar** [comment]
Yup, No worries! Thank you!

**Pull request merged**
