### PR TITLE
fix: the create-classroom modal changes size after user clicks drop-down menu

### LINKED ISSUE #151: Bug: The create-classroom modal changes size after user clicks drop-down menu
To reproduce: 
- Sign in with a Teacher account
- Go to the classes page
- Create class
- Select different courses from the drop-down menu.

### PR DESCRIPTION
**Pull request by imeltsner**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #151

Fixed the width of the create-class drop down menu so it doesn't expand.

https://user-images.githubusercontent.com/112027089/197363279-5331facf-2710-4c04-bf29-9512d415dfb6.mp4

### CODE REVIEW

**Comment by GuillermoFloresV** [comment]
Hi there, thanks for taking this issue. Would it be possible to show us a video of the new behavior of the modal when things are selected? It would help us see the change between the old and the new. Thanks!

**Comment by imeltsner** [comment]
> Hi there, thanks for taking this issue. Would it be possible to show us a video of the new behavior of the modal when things are selected? It would help us see the change between the old and the new. Thanks!

I added a video with the explanation to the pull request comments.

**Comment by GuillermoFloresV** [comment]
Awesome, great job! This looks good to me. @utsab I was thinking about also tagging this newly created issue, #167 since it's related to the UI of the modal. What do you think? Otherwise, this looks good to push.

**Comment by egall18** [comment]
Hey, there @imeltsner can you also make the same change in the edit feature under the ClassInviteTable.js component, for editOn modal, thank you.

**Review by egall18 — CHANGES_REQUESTED** [review]
Hey, there @imeltsner can you also make the same change in the edit feature under the ClassInviteTable.js component, for editOn modal, thank you. After that change then it should be good.

**Comment by Tichin** [comment]
Hi there, @egall18 I am from this micro-internship team. I'll be working on this.

**Comment by Templer44** [comment]
Hello @egall18, I'm also from this micro-internship team. I will begin work on this issue as soon as possible.

**Comment by Tichin** [comment]
Hi @egall18, I've made the same change to the editOn modal. Please review. Thanks.

**Review by egall18 — APPROVED** [review]

**Comment by egall18** [comment]
> Hi @egall18, I've made the same change to the editOn modal. Please review. Thanks.

LGTM

**Pull request merged**
