### PR TITLE
(docs): System diagram added with canva link

### LINKED ISSUE #372: Need an architectural and systems design diagram for the freeCodeCamp classroom project
**Describe the bug**
Need an architectural and systems design diagram for the freeCodeCamp classroom project

**To Reproduce**
1. Go to https://github.com/freeCodeCamp/classroom/
2. Read https://github.com/freeCodeCamp/classroom/#readme
3. Documentation references source code, but I don't see any architectural or system design diagrams
4. I could use an architectural and system design diagram based on the steps described in https://bit.ly/SystemDesignInterview

**Expected behavior**
An architectural and system design diagram hosted at https://excalidraw.com/ based on the steps described in https://bit.ly/SystemDesignInterview would be helpful to mentors like me.

**Additional context**
I am mentoring students working on freeCodeCamp/classroom and I am not understanding the architectural and system design of freeCodeCamp/classroom by reading https://github.com/freeCodeCamp/classroom/#readme — without diving deeper into the codebase.

### PR DESCRIPTION
**Pull request by Komal914**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #372

Co-authored-by: Natalia Gill <ngillux@gmail.com>
Co-authored-by: Lloyd Chang <lloydchang@gmail.com>

### CODE REVIEW

**Review by Komal914 — COMMENTED** [review]
Co-authored-by: Natalia Gill <ngillux@gmail.com>

**Review by Komal914 — COMMENTED** [review]
Co-authored-by: Natalia Gill <ngillux@gmail.com>

**Comment by lloydchang** [comment]
lgtm

**Comment by lloydchang** [comment]
:shipit: :ship: :it:

**Review by utsab — APPROVED** [review]

**Pull request merged**
