### PR TITLE
fix(134): Changed the invite, create, and delete banner to a more UX friendly design using toastify.

### PR DESCRIPTION
**Pull request by KevinTieu9**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Changed the invite, create, and delete banner to a more modern and more UX friendly design, the banner waits for a predefined timer before refreshing the page to show the user the new class. Images to show where and how the banner functions.

### CODE REVIEW

**Comment by KevinTieu9** [comment]
codeImports
deletedClass
Error
indexToast
successfullyCreatedClassSnippet

**Comment by yeeao** [comment]
image
image
image

**Comment by GuillermoFloresV** [comment]
Hi there @yeeao & @KevinTieu9 

There seems to be a conflict with the code inside of `components/ClassInviteTable.js`
This means that the code cannot be merged even if the code is "approved" by the team. If possible could you two work together to fix this conflict? It would be a great learning experience for you two since you're bound to deal with merge conflicts in the future. Once that is fixed we can get to work on reviewing/approving your changes.

**Comment by KevinTieu9** [comment]
@GuillermoFloresV it turns out there were a few missing code from the file. So we went ahead with fixing that portion of the code, it should be working. Although we will be making changing to this file again.

**Comment by KevinTieu9** [comment]
> Hi there @yeeao & @KevinTieu9
> 
> There seems to be a conflict with the code inside of `components/ClassInviteTable.js` This means that the code cannot be merged even if the code is "approved" by the team. If possible could you two work together to fix this conflict? It would be a great learning experience for you two since you're bound to deal with merge conflicts in the future. Once that is fixed we can get to work on reviewing/approving your changes.

I'll be working on it with the others, it seems the file has been updated since the PR, we will have a new file.

**Comment by utsab** [comment]
This PR is refactored as a newer PR, so we're not going to merge this one.

**Pull request closed without merging**
